name = "inhabit"
version = "0.1.0"
defaultTargets = ["inhabit"]

[[lean_lib]]
name = "Inhabit"

[[lean_exe]]
name = "inhabit"
root = "Main"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "main"